config/routes.rb
Rails.application.routes.draw do
  resources :vacinas

  root 'sessions#new'
  get 'sessions/new'
  get 'usuarios/new'

  resources :usuarios do
    resources :vacinacaos
  end

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
end

app/models/vacinacao.rb
class Vacinacao < ApplicationRecord
  belongs_to :usuario
  belongs_to :vacina

  validates :data, presence: true
  validates :horario, presence: true
  validates :desc_local, presence: true, length: {minimum: 5}


  def valida_data
    if  data.present? && data < Time.zone.today
      errors.add(:data, " A data deve ser futura")
    end
  end
end

app/controllers/vacinacaos_controller.rb
class VacinacaosController < ApplicationController
  before_action :set_vacinacao, only: %i[ show edit update destroy ]
  before_action :authorize


  # GET /vacinacaos or /vacinacaos.json
  def index

    if current_usuario.Admin?
      @vacinacaos = Vacinacao.all
    else
      @vacinacaos = current_usuario.vacinacaos
    end



  end

  # GET /vacinacaos/1 or /vacinacaos/1.json
  def show
  end

  # GET /vacinacaos/new
  def new
    @vacinacao = Vacinacao.new
    @vacinacao.build_vacina

  end

  # GET /vacinacaos/1/edit
  def edit
  end

  # POST /vacinacaos or /vacinacaos.json
  def create
    @vacinacao = Vacinacao.new(vacinacao_params)


    respond_to do |format|
      if @vacinacao.save
        format.html { redirect_to usuario_vacinacao_path(:usuario_id => current_usuario,:id => @vacinacao), notice: "Vacinacao was successfully created." }
        format.json { render :show, status: :created, location: @vacinacao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacinacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacinacaos/1 or /vacinacaos/1.json
  def update
    respond_to do |format|
      if @vacinacao.update(vacinacao_params)
        format.html { redirect_to usuario_vacinacao_path, notice: "Vacinacao was successfully updated." }
        format.json { render :show, status: :ok, location: @vacinacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacinacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacinacaos/1 or /vacinacaos/1.json
  def destroy
    @vacinacao.destroy

    respond_to do |format|
      format.html { redirect_to usuario_vacinacaos_path, notice: "Vacinacao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacinacao
      @vacinacao = Vacinacao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacinacao_params
      params.require(:vacinacao).permit(:desc_local, :data, :horario, :usuario_id, :vacina_id)
    end
end

app/helpers/vacinacaos_helper.rb
module VacinacaosHelper
  def usuario_vacinacao
    Vacinacao.where(usuario_id: current_usuario.id)
  end
end

app/views/vacinacaos/_form.html.erb
<%= form_with(model: [@current_usuario, vacinacao]) do |form| %>
  <% if vacinacao.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vacinacao.errors.count, "error") %> prohibited this vacinacao from being saved:</h2>

      <ul>
        <% vacinacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :desc_local, style: "display: block" %>
    <%= form.text_field :desc_local %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div>
    <%= form.label :horario, style: "display: block" %>
    <%= form.time_field :horario %>
  </div>

  <div>
    <%= form.label :vacina_id, style: "display: block" %>
    <%= form.collection_select(:vacina_id, Vacina.all, :id, :nome_vacina, {:selected => @vacinacao.vacina_id}, {class: "form-control"})%>

  </div>

  <% if current_usuario.Admin?  %>
  <div>
    <%= form.label :usuario_id, style: "display: block" %>
    <%= form.text_field :usuario_id, value: params[:usuario_id] %>
  </div>

  <% else %>
    <div>
      <%= form.label :usuario_id, style: "display: block" %>
      <%= form.hidden_field :usuario_id, value: params[:usuario_id] %>
    </div>

  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vacinacaos/_vacinacao.html.erb
<div id="<%= dom_id vacinacao %>">
  <p>
    <strong>Desc local:</strong>
    <%= vacinacao.desc_local %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= vacinacao.data %>
  </p>

  <p>
    <strong>Horario:</strong>
    <%= vacinacao.horario %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= vacinacao.usuario_id %>
  </p>

</div>

app/views/vacinacaos/edit.html.erb
<h1>Editing vacinacao</h1>

<%= render "form", vacinacao: @vacinacao %>

<br>

<div>
  <%= link_to "Show this vacinacao", usuario_vacinacao_path(:usuario_id => current_usuario,:id => @vacinacao)%> |
  <%= link_to "Back to vacinacaos", usuario_vacinacaos_path(:usuario_id => current_usuario) %>
</div>

app/views/vacinacaos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vacinacaos</h1>

<div id="vacinacaos">
  <% @vacinacaos.each do |vacinacao| %>
    <%= render vacinacao %>
    <p>
      <%= link_to "Show this vacinacao", usuario_vacinacao_path(:usuario_id => current_usuario,:id => vacinacao) %>
    </p>
  <% end %>
</div>

<%= link_to "New vacinacao", new_usuario_vacinacao_path %>

app/views/vacinacaos/new.html.erb
<h1>New vacinacao</h1>

<%= render "form", vacinacao: @vacinacao %>

<br>

<div>
  <%= link_to "Back to vacinacaos", usuario_vacinacaos_path %>
</div>

app/views/vacinacaos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vacinacao %>

<div>
  <%= link_to "Edit this vacinacao", edit_usuario_vacinacao_path(:usuario_id => current_usuario,:id => @vacinacao) %> |
  <%= link_to "Back to vacinacaos", usuario_vacinacaos_path(:usuario_id => current_usuario,:id => @vacinacao) %>

  <%= button_to "Destroy this vacinacao", usuario_vacinacao_path(:usuario_id => current_usuario,:id => @vacinacao), method: :delete %>
</div>