config/routes.rb
Rails.application.routes.draw do
  resources :vacinas

  root 'sessions#new'
  get 'sessions/new'
  get 'usuarios/new'

  resources :usuarios do
    resources :vacinacaos
  end

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
end

app/models/vacina.rb
class Vacina < ApplicationRecord


  has_one :vacinacao

  validates :nome_vacina, presence: true
  validates :num_lote, presence: true
  validates :data_validade, presence: true
  validate :valida_data

  def valida_data
    if  data_validade.present? && data_validade < Time.zone.today
      errors.add(:data, " A data deve ser futura")
    end
  end


end

app/controllers/vacinas_controller.rb
class VacinasController < ApplicationController
  before_action :set_vacina, only: %i[ show edit update destroy ]
  before_action :authorize_admin

  # GET /vacinas or /vacinas.json
  def index

    @vacinas = Vacina.all
  end

  # GET /vacinas/1 or /vacinas/1.json
  def show
  end

  # GET /vacinas/new
  def new
    @vacina = Vacina.new
  end

  # GET /vacinas/1/edit
  def edit
  end

  # POST /vacinas or /vacinas.json
  def create
    @vacina = Vacina.new(vacina_params)

    respond_to do |format|
      if @vacina.save
        format.html { redirect_to vacina_url(@vacina), notice: "Vacina was successfully created." }
        format.json { render :show, status: :created, location: @vacina }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacinas/1 or /vacinas/1.json
  def update
    respond_to do |format|
      if @vacina.update(vacina_params)
        format.html { redirect_to vacina_url(@vacina), notice: "Vacina was successfully updated." }
        format.json { render :show, status: :ok, location: @vacina }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacinas/1 or /vacinas/1.json
  def destroy
    @vacina.destroy

    respond_to do |format|
      format.html { redirect_to vacinas_url, notice: "Vacina was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacina
      @vacina = Vacina.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacina_params
      params.require(:vacina).permit(:nome_vacina, :num_lote, :data_validade)
    end
end

app/helpers/vacinas_helper.rb
module VacinasHelper
end

app/views/vacinas/_form.html.erb
<%= form_with(model: vacina) do |form| %>
  <% if vacina.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vacina.errors.count, "error") %> prohibited this vacina from being saved:</h2>

      <ul>
        <% vacina.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome_vacina, style: "display: block" %>
    <%= form.text_field :nome_vacina %>
  </div>

  <div>
    <%= form.label :num_lote, style: "display: block" %>
    <%= form.text_field :num_lote %>
  </div>

  <div>
    <%= form.label :data_validade, style: "display: block" %>
    <%= form.date_field :data_validade %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vacinas/_vacina.html.erb
<div id="<%= dom_id vacina %>">
  <p>
    <strong>Nome vacina:</strong>
    <%= vacina.nome_vacina %>
  </p>

  <p>
    <strong>Num lote:</strong>
    <%= vacina.num_lote %>
  </p>

  <p>
    <strong>Data validade:</strong>
    <%= vacina.data_validade %>
  </p>

</div>

app/views/vacinas/edit.html.erb
<h1>Editing vacina</h1>

<%= render "form", vacina: @vacina %>

<br>

<div>
  <%= link_to "Show this vacina", @vacina %> |
  <%= link_to "Back to vacinas", vacinas_path %>
</div>

app/views/vacinas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vacinas</h1>

<div id="vacinas">
  <% @vacinas.each do |vacina| %>
    <%= render vacina %>
    <p>
      <%= link_to "Show this vacina", vacina %>
    </p>
  <% end %>
</div>

<%= link_to "New vacina", new_vacina_path %>

app/views/vacinas/new.html.erb
<h1>New vacina</h1>

<%= render "form", vacina: @vacina %>

<br>

<div>
  <%= link_to "Back to vacinas", vacinas_path %>
</div>

app/views/vacinas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vacina %>

<div>
  <%= link_to "Edit this vacina", edit_vacina_path(@vacina) %> |
  <%= link_to "Back to vacinas", vacinas_path %>

  <%= button_to "Destroy this vacina", @vacina, method: :delete %>
</div>