config/routes.rb
Rails.application.routes.draw do
  resources :vacinas

  root 'sessions#new'
  get 'sessions/new'
  get 'usuarios/new'

  resources :usuarios do
    resources :vacinacaos
  end

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password

  has_one :endereco, :dependent => :destroy
  has_many :vacinacaos
  accepts_nested_attributes_for :endereco, allow_destroy: true

  validates :nome_completo, presence: true, length: {minimum:5}, numericality: false
  validate :valida_data
  validates :cpf, presence: true, uniqueness: true, length: {is: 11}
  validates :nome_mae, presence: true, length: {minimum:5}
  validates :num_sus, presence: true, length: {minimum:6}
  validates :email, presence: true, length:{maximum: 255}, uniqueness:{case_sensitive: true}
  validates :telefone, presence: true, length: {minimum:8}
  validates :password, presence: true, length: {minimum:6}

  def valida_data
    if  data_nascimento.present? && data_nascimento > Time.zone.today
      errors.add(:data, " A data deve ser de hoje ou anterior")
    end
  end

  # Roles available to each user
  enum role: { Usuario: 0, Admin: 1 }
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :usuario
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authorize, except: [:new, :create]
  before_action :correct_usuario?, only: [:edit, :update, :destroy]
  before_action :authorize_admin, except: [:new, :create, :show]

  def new
    @usuario = Usuario.new
    @usuario.build_endereco
  end

  def create
    @usuario = Usuario.new(usuario_params)

    if @usuario.save
      flash[:success] = "Usuario cadastrado"
      redirect_to root_path

    else
      render 'new'
    end
  end

  def index

    if current_usuario.Admin?
      @usuarios = Usuario.all
    else
      flash[:danger] = "Voce nao tem privilegios no sistema"
      redirect_to root_path
    end

  end

  def show
    @usuario = Usuario.find(params[:id])
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])
    if current_usuario.update(usuario_params)
      redirect_to @usuario, notice: "Usuario atualizado com sucesso"

    else
      render action: :edit
    end
  end

  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Usuário foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private


  def usuario_params
    params.require(:usuario).permit(:role, :nome_completo, :data_nascimento,:cpf,:nome_mae, :telefone, :email, :num_sus, :password,{:endereco_attributes => [:id, :logradouro, :complemento, :cep, :bairro, :cidade]})

  end

end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: @usuario, local: true) do |form| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% @usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_completo %>
    <%= form.text_field :nome_completo %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.date_field :data_nascimento %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.number_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.number_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :nome_mae %>
    <%= form.text_field :nome_mae %>
  </div>

  <div class="field">
    <%= form.label :num_sus %>
    <%= form.text_field :num_sus %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.select :role, options_for_select([:Usuario, :Admin]) %>
  </div>

 <%= form.fields_for :endereco do |endereco_form| %>
    Cidade  : <%= endereco_form.text_field :cidade %>
    Logradouro  : <%= endereco_form.text_field :logradouro %>
    Complemento  : <%= endereco_form.text_field :complemento %>
    Bairro  : <%= endereco_form.text_field :bairro %>
    Cep: <%= endereco_form.text_field :cep %>
  <% end %>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editar Dados</h1>

<%= form_for current_usuario do |form|%>

  <%=render 'form', form: form%>
<% end %>

app/views/usuarios/index.html.erb
<h1> Users </h1>
<table>
  <thead>
  <tr>
    <th>CPF</th>
    <th>Email</th>
    <th></th>
  </tr>
  </thead>

  <% @usuarios.each do |user| %>
    <tr>
      <td><%= user.cpf %></td>
      <td><%= user.email %></td>
      <td><%= link_to "Show", user %></td>
    </tr>
  <%end%>
  <%= link_to "Ver vacinacaos", usuario_vacinacaos_path(:usuario_id => current_usuario,:id => @vacinacao) %>
  </br>
  <%= link_to "Ver vacinas", vacinas_path %>
  </tbody>
</table>

app/views/usuarios/new.html.erb
<h1>Cadastro de Usuarios</h1>
<p>Find me in app/views/usuarios/new.html.erb</p>

<%= form_for @usuario do |form|%>

  <%=render 'form', form: form%>
<% end %>

app/views/usuarios/show.html.erb
<h2>Show de Usuario</h2>

<p>
  <strong>Nome Completo:</strong>
  <%= current_usuario.nome_completo %>
</p>

<p>
  <strong>Data de Nascimento:</strong>
  <%= current_usuario.data_nascimento %>
</p>

<p>
  <strong>Nome da mãe:</strong>
  <%= current_usuario.nome_mae %>
</p>

<p>
  <strong>CPF:</strong>
  <%= current_usuario.cpf %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= current_usuario.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= current_usuario.email %>
</p>


<p>
  <strong>CEP:</strong>
  <%= current_usuario.endereco.cep %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= current_usuario.endereco.cidade %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= current_usuario.endereco.bairro %>
</p>

<p>
  <strong>Logradouro:</strong>
  <%= current_usuario.endereco.logradouro %>
</p>

<p>
  <strong>Completo:</strong>
  <%= current_usuario.endereco.complemento %>
</p>


<%= link_to 'Editar dados', edit_usuario_path(current_usuario)%>
<%= button_to "Sair", sign_out_path, method: :delete %>
<%= button_to "Destroy this usuario", @usuario, method: :delete %>
<%= link_to 'Nova Vacinacao', new_usuario_vacinacao_path(:usuario_id => current_usuario)%>